services:
  redis-server:
    image: "redis"
    volumes:
      - ./redis:/data
    command: ["redis-server", "--save", "1 1",
             "--protected-mode", "no"]
  node-app:
    restart: always
    build: .
    ports:
      - "8081:8081"
